/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.epizy.mulialaksanasejahtera.View.JInternalFrame;

import com.epizy.mulialaksanasejahtera.Controller.controllerConfig;
import com.epizy.mulialaksanasejahtera.DataBaseConncetion.dataBaseConncetionFactory;
import mv.lib.ProsesDB.GetDataFromDB;

import javax.swing.plaf.basic.BasicInternalFrameUI;
import java.awt.*;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;

/**
 *
 * @author Wisnu_Putra_Dewa
 */
public class data_diri_baru extends javax.swing.JInternalFrame {

    /**
     * Creates new form data_diri_baru
     */
    GetDataFromDB gdfdb=new GetDataFromDB();
    final controllerConfig config = new controllerConfig();
    public final String parameter=home.par;
    public data_diri_baru() {
        BasicInternalFrameUI bi = (BasicInternalFrameUI)this.getUI();
        bi.setNorthPane(null);
        initComponents();
        grabdata(parameter);
    }
    private void grabdata(String par){
        String sql = "SELECT * FROM `data_pribadi` WHERE `no_reg` = ?";
        PreparedStatement preparedStatement;
        try {
            preparedStatement = dataBaseConncetionFactory.getConnection().prepareStatement(sql);
            preparedStatement.setString(1,par);
            ResultSet resultSet = preparedStatement.executeQuery();
            while (resultSet.next()) {
                kelamin.setText(resultSet.getString(3));
                no_ktp.setText(resultSet.getString(5));
                tempat_ktp.setText(resultSet.getString(6));
                tgl_ktp.setText(resultSet.getString(7));
                nama.setText("Data Diri Dari : "+resultSet.getString(8));
                usia.setText(resultSet.getString(9));
                alamat.setText(resultSet.getString(10));
                desa_kel.setText(resultSet.getString(11));
                kecamatan.setText(resultSet.getString(12));
                kab_kota.setText(resultSet.getString(13));
                propinsi.setText(resultSet.getString(14));
                tempat_lahir.setText(resultSet.getString(15));
                tgl_lahir.setText(resultSet.getString(16));
                no_tlp.setText(resultSet.getString(17));
                no_hp.setText(resultSet.getString(18));
                tinggi.setText(resultSet.getString(19));
                berat.setText(resultSet.getString(20));
                setatus.setText(resultSet.getString(21));
                tgl_setatus.setText(resultSet.getString(22));
                pendidikan.setText(resultSet.getString(23));
                agama.setText(resultSet.getString(24));
                jPanel2.setMaximumSize(new Dimension(1000,200));
                jPanel2.setMinimumSize(new Dimension(1000,200));
                config.getIamge(resultSet.getString(25), gambar);
                email.setText(resultSet.getString(26));
                ket.setText(resultSet.getString(27));
            }
        }catch (SQLException e) {
            e.printStackTrace();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.JPanel jPanel4 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        javax.swing.JLabel jLabel3 = new javax.swing.JLabel();
        javax.swing.JLabel jLabel5 = new javax.swing.JLabel();
        javax.swing.JLabel jLabel7 = new javax.swing.JLabel();
        kelamin = new javax.swing.JLabel();
        alamat = new javax.swing.JLabel();
        kab_kota = new javax.swing.JLabel();
        javax.swing.JLabel jLabel8 = new javax.swing.JLabel();
        javax.swing.JLabel jLabel10 = new javax.swing.JLabel();
        javax.swing.JLabel jLabel6 = new javax.swing.JLabel();
        javax.swing.JLabel jLabel11 = new javax.swing.JLabel();
        tgl_ktp = new javax.swing.JLabel();
        desa_kel = new javax.swing.JLabel();
        kecamatan = new javax.swing.JLabel();
        javax.swing.JLabel jLabel13 = new javax.swing.JLabel();
        javax.swing.JLabel jLabel14 = new javax.swing.JLabel();
        javax.swing.JLabel jLabel15 = new javax.swing.JLabel();
        javax.swing.JLabel jLabel16 = new javax.swing.JLabel();
        javax.swing.JLabel jLabel17 = new javax.swing.JLabel();
        javax.swing.JLabel jLabel18 = new javax.swing.JLabel();
        javax.swing.JLabel jLabel4 = new javax.swing.JLabel();
        no_ktp = new javax.swing.JLabel();
        javax.swing.JLabel jLabel9 = new javax.swing.JLabel();
        tempat_ktp = new javax.swing.JLabel();
        propinsi = new javax.swing.JLabel();
        javax.swing.JLabel jLabel19 = new javax.swing.JLabel();
        javax.swing.JLabel jLabel20 = new javax.swing.JLabel();
        javax.swing.JLabel jLabel21 = new javax.swing.JLabel();
        tgl_lahir = new javax.swing.JLabel();
        no_tlp = new javax.swing.JLabel();
        no_hp = new javax.swing.JLabel();
        tinggi = new javax.swing.JLabel();
        berat = new javax.swing.JLabel();
        setatus = new javax.swing.JLabel();
        tgl_setatus = new javax.swing.JLabel();
        pendidikan = new javax.swing.JLabel();
        agama = new javax.swing.JLabel();
        javax.swing.JSeparator jSeparator2 = new javax.swing.JSeparator();
        nama = new javax.swing.JLabel();
        usia = new javax.swing.JLabel();
        javax.swing.JLabel jLabel22 = new javax.swing.JLabel();
        javax.swing.JLabel jLabel23 = new javax.swing.JLabel();
        tempat_lahir = new javax.swing.JLabel();
        gambar = new javax.swing.JLabel();
        javax.swing.JPanel jPanel3 = new javax.swing.JPanel();
        javax.swing.JLabel jLabel1 = new javax.swing.JLabel();
        ket = new javax.swing.JLabel();
        javax.swing.JLabel jLabel12 = new javax.swing.JLabel();
        email = new javax.swing.JLabel();

        setBackground(new java.awt.Color(204, 204, 204));
        setBorder(null);

        jPanel4.setBackground(new java.awt.Color(204, 204, 204));

        jPanel2.setBackground(new java.awt.Color(102, 255, 102));

        jLabel3.setFont(new java.awt.Font("Dialog", Font.BOLD, 14)); // NOI18N
        jLabel3.setText("Kelamin :");

        jLabel5.setFont(new java.awt.Font("Dialog", Font.BOLD, 14)); // NOI18N
        jLabel5.setText("Alamat :");

        jLabel7.setFont(new java.awt.Font("Dialog", Font.BOLD, 14)); // NOI18N
        jLabel7.setText("Propinsi :");

        kelamin.setFont(new java.awt.Font("Dialog", Font.BOLD, 14)); // NOI18N
        kelamin.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        kelamin.setText("isi data");

        alamat.setFont(new java.awt.Font("Dialog", Font.BOLD, 14)); // NOI18N
        alamat.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        alamat.setText("isi data");

        kab_kota.setFont(new java.awt.Font("Dialog", Font.BOLD, 14)); // NOI18N
        kab_kota.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        kab_kota.setText("isi data");

        jLabel8.setFont(new java.awt.Font("Dialog", Font.BOLD, 14)); // NOI18N
        jLabel8.setText("Kabupaten/Kota :");

        jLabel10.setFont(new java.awt.Font("Dialog", Font.BOLD, 14)); // NOI18N
        jLabel10.setText("Tanggal KTP Dibuat :");

        jLabel6.setFont(new java.awt.Font("Dialog", Font.BOLD, 14)); // NOI18N
        jLabel6.setText("Desa/Kelurahan :");

        jLabel11.setFont(new java.awt.Font("Dialog", Font.BOLD, 14)); // NOI18N
        jLabel11.setText("Kecamatan :");

        tgl_ktp.setFont(new java.awt.Font("Dialog", Font.BOLD, 14)); // NOI18N
        tgl_ktp.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        tgl_ktp.setText("isi data");

        desa_kel.setFont(new java.awt.Font("Dialog", Font.BOLD, 14)); // NOI18N
        desa_kel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        desa_kel.setText("isi data");

        kecamatan.setFont(new java.awt.Font("Dialog", Font.BOLD, 14)); // NOI18N
        kecamatan.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        kecamatan.setText("isi data");

        jLabel13.setFont(new java.awt.Font("Dialog", Font.BOLD, 14)); // NOI18N
        jLabel13.setText("Tanggal Lahir :");

        jLabel14.setFont(new java.awt.Font("Dialog", Font.BOLD, 14)); // NOI18N
        jLabel14.setText("No. Telepon :");

        jLabel15.setFont(new java.awt.Font("Dialog", Font.BOLD, 14)); // NOI18N
        jLabel15.setText("No. HP/Flexy :");

        jLabel16.setFont(new java.awt.Font("Dialog", Font.BOLD, 14)); // NOI18N
        jLabel16.setText("Tinggi Badan :");

        jLabel17.setFont(new java.awt.Font("Dialog", Font.BOLD, 14)); // NOI18N
        jLabel17.setText("Berat Badan :");

        jLabel18.setFont(new java.awt.Font("Dialog", Font.BOLD, 14)); // NOI18N
        jLabel18.setText("Setatus :");

        jLabel4.setFont(new java.awt.Font("Dialog", Font.BOLD, 14)); // NOI18N
        jLabel4.setText("No KTP :");

        no_ktp.setFont(new java.awt.Font("Dialog", Font.BOLD, 14)); // NOI18N
        no_ktp.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        no_ktp.setText("isi data");

        jLabel9.setFont(new java.awt.Font("Dialog", Font.BOLD, 14)); // NOI18N
        jLabel9.setText("Tempat KTP Dibuat :");

        tempat_ktp.setFont(new java.awt.Font("Dialog", Font.BOLD, 14)); // NOI18N
        tempat_ktp.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        tempat_ktp.setText("isi data");

        propinsi.setFont(new java.awt.Font("Dialog", Font.BOLD, 14)); // NOI18N
        propinsi.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        propinsi.setText("isi data");

        jLabel19.setFont(new java.awt.Font("Dialog", Font.BOLD, 14)); // NOI18N
        jLabel19.setText("Tanggal Setatus :");

        jLabel20.setFont(new java.awt.Font("Dialog", Font.BOLD, 14)); // NOI18N
        jLabel20.setText("Pendidikan Teraakhir :");

        jLabel21.setFont(new java.awt.Font("Dialog", Font.BOLD, 14)); // NOI18N
        jLabel21.setText("Agama :");

        tgl_lahir.setFont(new java.awt.Font("Dialog", Font.BOLD, 14)); // NOI18N
        tgl_lahir.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        tgl_lahir.setText("isi data");

        no_tlp.setFont(new java.awt.Font("Dialog", Font.BOLD, 14)); // NOI18N
        no_tlp.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        no_tlp.setText("isi data");

        no_hp.setFont(new java.awt.Font("Dialog", Font.BOLD, 14)); // NOI18N
        no_hp.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        no_hp.setText("isi data");

        tinggi.setFont(new java.awt.Font("Dialog", Font.BOLD, 14)); // NOI18N
        tinggi.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        tinggi.setText("isi data");

        berat.setFont(new java.awt.Font("Dialog", Font.BOLD, 14)); // NOI18N
        berat.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        berat.setText("isi data");

        setatus.setFont(new java.awt.Font("Dialog", Font.BOLD, 14)); // NOI18N
        setatus.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        setatus.setText("isi data");

        tgl_setatus.setFont(new java.awt.Font("Dialog", Font.BOLD, 14)); // NOI18N
        tgl_setatus.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        tgl_setatus.setText("isi data");

        pendidikan.setFont(new java.awt.Font("Dialog", Font.BOLD, 14)); // NOI18N
        pendidikan.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        pendidikan.setText("isi data");

        agama.setFont(new java.awt.Font("Dialog", Font.BOLD, 14)); // NOI18N
        agama.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        agama.setText("isi data");

        jSeparator2.setBackground(new java.awt.Color(255, 255, 255));
        jSeparator2.setForeground(new java.awt.Color(153, 153, 153));

        nama.setFont(new java.awt.Font("Dialog", Font.BOLD, 18)); // NOI18N
        nama.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        nama.setText("Data Diri");

        usia.setFont(new java.awt.Font("Dialog", Font.BOLD, 14)); // NOI18N
        usia.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        usia.setText("isi data");

        jLabel22.setFont(new java.awt.Font("Dialog", Font.BOLD, 14)); // NOI18N
        jLabel22.setText("Usia :");

        jLabel23.setFont(new java.awt.Font("Dialog", Font.BOLD, 14)); // NOI18N
        jLabel23.setText("Tempat Lahir :");

        tempat_lahir.setFont(new java.awt.Font("Dialog", Font.BOLD, 14)); // NOI18N
        tempat_lahir.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        tempat_lahir.setText("isi data");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator2, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(nama, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(4, 4, 4))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel23, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(18, 18, 18)
                                .addComponent(tempat_lahir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, 173, Short.MAX_VALUE)
                                .addGap(18, 18, 18)
                                .addComponent(tgl_ktp, javax.swing.GroupLayout.DEFAULT_SIZE, 81, Short.MAX_VALUE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGap(66, 66, 66)))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(kelamin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(no_ktp, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(18, 18, 18)
                                .addComponent(tempat_ktp, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(18, 18, 18)
                                .addComponent(kab_kota, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(18, 18, 18)
                                .addComponent(propinsi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(18, 18, 18)
                                .addComponent(alamat, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(18, 18, 18)
                                .addComponent(desa_kel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(18, 18, 18)
                                .addComponent(kecamatan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(22, 22, 22)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGap(18, 18, 18)
                                        .addComponent(no_tlp, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(jLabel15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGap(18, 18, 18)
                                        .addComponent(no_hp, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(jLabel16, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGap(18, 18, 18)
                                        .addComponent(tinggi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(jLabel17, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGap(18, 18, 18)
                                        .addComponent(berat, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(jLabel19, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGap(18, 18, 18)
                                        .addComponent(tgl_setatus, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(jLabel20, javax.swing.GroupLayout.DEFAULT_SIZE, 186, Short.MAX_VALUE)
                                        .addGap(18, 18, 18)
                                        .addComponent(pendidikan, javax.swing.GroupLayout.DEFAULT_SIZE, 81, Short.MAX_VALUE))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)
                                        .addGap(18, 18, 18)
                                        .addComponent(agama, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)
                                        .addGap(18, 18, 18)
                                        .addComponent(setatus, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)
                                        .addGap(18, 18, 18)
                                        .addComponent(usia, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(18, 18, 18)
                                .addComponent(tgl_lahir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(nama, javax.swing.GroupLayout.DEFAULT_SIZE, 26, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(kelamin)
                    .addComponent(jLabel13)
                    .addComponent(tgl_lahir))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel22)
                        .addComponent(usia, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel4)
                        .addComponent(no_ktp)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(tempat_ktp)
                    .addComponent(jLabel14)
                    .addComponent(no_tlp))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(tgl_ktp)
                    .addComponent(jLabel15)
                    .addComponent(no_hp))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(alamat, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel16)
                    .addComponent(tinggi))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(desa_kel, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel17)
                    .addComponent(berat))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(kecamatan, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel18)
                    .addComponent(setatus))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(kab_kota, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel19)
                        .addComponent(tgl_setatus)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(propinsi, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel20)
                        .addComponent(pendidikan)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel23)
                    .addComponent(tempat_lahir)
                    .addComponent(jLabel21)
                    .addComponent(agama))
                .addContainerGap())
        );

        gambar.setBackground(new java.awt.Color(102, 255, 102));
        gambar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        gambar.setText("Gambar");
        gambar.setToolTipText("");
        gambar.setPreferredSize(new java.awt.Dimension(200, 200));

        jPanel3.setBackground(new java.awt.Color(102, 255, 102));

        jLabel1.setFont(new java.awt.Font("Dialog", Font.BOLD, 14)); // NOI18N
        jLabel1.setText("Pernah mengikuti Pendidikan Non Formal/ Sertifikat Ketrampilan /kursus :");

        ket.setFont(new java.awt.Font("Dialog", Font.BOLD, 14)); // NOI18N
        ket.setText("jLabel2");

        jLabel12.setFont(new java.awt.Font("Dialog", Font.BOLD, 14)); // NOI18N
        jLabel12.setText("Email :");

        email.setFont(new java.awt.Font("Dialog", Font.BOLD, 14)); // NOI18N
        email.setText("jLabel65");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(ket, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(462, 462, 462)))
                        .addGap(217, 217, 217))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel12)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(email)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(email))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ket)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(gambar, javax.swing.GroupLayout.PREFERRED_SIZE, 296, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(gambar, javax.swing.GroupLayout.PREFERRED_SIZE, 308, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(88, 88, 88))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel agama;
    private javax.swing.JLabel alamat;
    private javax.swing.JLabel berat;
    private javax.swing.JLabel desa_kel;
    private javax.swing.JLabel email;
    private javax.swing.JLabel gambar;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel kab_kota;
    private javax.swing.JLabel kecamatan;
    private javax.swing.JLabel kelamin;
    private javax.swing.JLabel ket;
    private javax.swing.JLabel nama;
    private javax.swing.JLabel no_hp;
    private javax.swing.JLabel no_ktp;
    private javax.swing.JLabel no_tlp;
    private javax.swing.JLabel pendidikan;
    private javax.swing.JLabel propinsi;
    private javax.swing.JLabel setatus;
    private javax.swing.JLabel tempat_ktp;
    private javax.swing.JLabel tempat_lahir;
    private javax.swing.JLabel tgl_ktp;
    private javax.swing.JLabel tgl_lahir;
    private javax.swing.JLabel tgl_setatus;
    private javax.swing.JLabel tinggi;
    private javax.swing.JLabel usia;
    // End of variables declaration//GEN-END:variables
}
